@startuml
namespace proxy {
    class Car << (S,Aquamarine) >> {
        + Drive() 

    }
    class CarProxy << (S,Aquamarine) >> {
        - car Car
        - driver *Driver

        + Drive() 

    }
    interface Driven  {
        + Drive() 

    }
    class Driver << (S,Aquamarine) >> {
        + Age int

    }
}

"proxy.Driven" <|-- "proxy.Car"
"proxy.Driven" <|-- "proxy.CarProxy"

@enduml
