@startuml
namespace main {
    class Bitmap << (S,Aquamarine) >> {
        - filename string

        + Draw() 

    }
    interface Image  {
        + Draw() 

    }
    class LazyBitmap << (S,Aquamarine) >> {
        - filename string
        - bitmap *Bitmap

        + Draw() 

    }
}

"main.Image" <|-- "main.Bitmap"
"main.Image" <|-- "main.LazyBitmap"

@enduml
